// <auto-generated />
namespace EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Createdatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createdatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202004190306030_Create-database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
