//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHocPhan
    {
        public int Id { get; set; }
        public int IdSinhVien { get; set; }
        public int IdHocPhan { get; set; }
    
        public virtual HocPhan HocPhan { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
